version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm --prefix to-do-list-aws ci
  build:
    commands:
      - npm --prefix to-do-list-aws run build -- --configuration production
  post_build:
    commands:
      - aws s3 sync to-do-list-aws/dist/to-do-list-aws/browser s3://gc-static-bucket-22 --delete