version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
  build:
    commands:
      - npm run build -- --configuration production
  post_build:
    commands:
      # Copy compiled assets directly to S3
      - aws s3 sync dist/to-do-list-aws/browser s3://gc-static-bucket-22 --delete
      # Clear CloudFront cache (replace YOUR_CLOUDFRONT_DISTRIBUTION_ID)
      - aws cloudfront create-invalidation --distribution-id E2X36TAAPTGAHT --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: dist/to-do-list-aws/browser